<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoundCore.EstructurasPropias\SoundCore.EstructurasPropias.csproj" />
    <ProjectReference Include="..\SoundCore.Modelos\SoundCore.Modelos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Fleetwood Mac - The Chain %28Official Audio%29.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Metro Boomin, A%24AP Rocky, Roisee - Am I Dreaming %28Visualizer%29.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Pitbull - Fireball %28Official Video%29 ft. John Ryan.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>